"""add_frame_hashes_for_video_chaining

Revision ID: 1f69b8a67f30
Revises: f10b11038e4b
Create Date: 2025-10-22 11:28:58.569553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f69b8a67f30'
down_revision = 'f10b11038e4b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('child_posts', sa.Column('first_frame_hash', sa.String(length=64), nullable=True))
    op.add_column('child_posts', sa.Column('last_frame_hash', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_child_posts_first_frame_hash'), 'child_posts', ['first_frame_hash'], unique=False)
    op.create_index(op.f('ix_child_posts_last_frame_hash'), 'child_posts', ['last_frame_hash'], unique=False)
    op.add_column('media_posts', sa.Column('first_frame_hash', sa.String(length=64), nullable=True))
    op.add_column('media_posts', sa.Column('last_frame_hash', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_media_posts_first_frame_hash'), 'media_posts', ['first_frame_hash'], unique=False)
    op.create_index(op.f('ix_media_posts_last_frame_hash'), 'media_posts', ['last_frame_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_media_posts_last_frame_hash'), table_name='media_posts')
    op.drop_index(op.f('ix_media_posts_first_frame_hash'), table_name='media_posts')
    op.drop_column('media_posts', 'last_frame_hash')
    op.drop_column('media_posts', 'first_frame_hash')
    op.drop_index(op.f('ix_child_posts_last_frame_hash'), table_name='child_posts')
    op.drop_index(op.f('ix_child_posts_first_frame_hash'), table_name='child_posts')
    op.drop_column('child_posts', 'last_frame_hash')
    op.drop_column('child_posts', 'first_frame_hash')
    # ### end Alembic commands ###
