"""Add collections and collection_items tables

Revision ID: 659065ceb01f
Revises: 
Create Date: 2025-10-19 03:43:34.013894

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '659065ceb01f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collections',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_smart', sa.Boolean(), nullable=False),
    sa.Column('smart_filters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collections_user_id'), 'collections', ['user_id'], unique=False)
    op.create_table('collection_items',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('collection_id', sa.UUID(), nullable=False),
    sa.Column('media_post_id', sa.UUID(), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['media_post_id'], ['media_posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_unique_collection_post', 'collection_items', ['collection_id', 'media_post_id'], unique=True)
    op.create_index(op.f('ix_collection_items_collection_id'), 'collection_items', ['collection_id'], unique=False)
    op.create_index(op.f('ix_collection_items_media_post_id'), 'collection_items', ['media_post_id'], unique=False)
    op.create_index('idx_child_mode_model', 'child_posts', ['mode', 'model_name'], unique=False)
    op.create_index('idx_child_original_prompt', 'child_posts', ['original_prompt'], unique=False)
    op.create_index(op.f('ix_child_posts_mode'), 'child_posts', ['mode'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_child_posts_mode'), table_name='child_posts')
    op.drop_index('idx_child_original_prompt', table_name='child_posts')
    op.drop_index('idx_child_mode_model', table_name='child_posts')
    op.drop_index(op.f('ix_collection_items_media_post_id'), table_name='collection_items')
    op.drop_index(op.f('ix_collection_items_collection_id'), table_name='collection_items')
    op.drop_index('idx_unique_collection_post', table_name='collection_items')
    op.drop_table('collection_items')
    op.drop_index(op.f('ix_collections_user_id'), table_name='collections')
    op.drop_table('collections')
    # ### end Alembic commands ###
